### ISSUE TITLE
DropZone cannot be nested

### ISSUE THREAD

**Issue by feugy** [marcojakob/dart-html5-dnd#11]
Nested dropzone are not possible.
For example :

``` html
   <div class="main">
     <div class="child"></div>
  </div>
```

If I attach a dropzone on main, on a particular type of draggable, and if I attache another dropzone on child, with another type of draggable, operation is possible on main, but never on child.

It seems that main "isAcceptable" test will always be taken in account, even when hovering child zone.

**Comment by marcojakob** [comment]
Part of this is intended behaviour: When dragging over nested elements a drop should be accepted by all child elements. This means for your case that the draggable attached to `main` will also be accepted when dragged over the `child`.

But there seems to be a problem with the draggable that is attached to `child`. It should be accepted by `child` but is not.

I've created a test case in commit 3d54d09d3dcf8bf7317f41cbb3f903f166be8e71 which shows the problem but I don't know if I can fix it with all those events flying around in different browsers.

**Comment by feugy** [comment]
It seems to me natural that child zone accepts draggable that match main conditions.
I'm looking for your fix :)

**Comment by marc-hughes** [comment]
That commit doesn't really fix this issue.

It does fix the nested_dropzones_test.html test, but it doesn't allow nested draggables to work correctly.  There is a new test that shows that here: https://github.com/ScrumDoLLC/dart-html5-dnd/commit/98a9fec8290253b57b154dcbf3106d2b14ed5079

**Comment by marcojakob** [comment]
I can't look into that at the moment. But if you can provide a fix with a test as a pull request I can include it.
