### ISSUE TITLE
Element cannot be associated with multiple DropzoneGroup instances?

### ISSUE THREAD

**Issue by jbaxe2** [marcojakob/dart-html5-dnd#12]
I have a group of elements that is set up with two different DropzoneGroup instances, whereby each DropzoneGroup is established with different DraggableGroup instances.

The first DropzoneGroup to accept the DraggableGroup elements works fine, but the second one seems to be canceled.  Doesn't matter which one is used (user action of drag and drop) first.  Then, after the second group fails, the first one will fail.

For example:

``` dart
DraggableGroup draggables1 = new DraggableGroup()
  ..installAll (queryAll ('.some-group-of-draggables-1'));

DraggableGroup draggables2 = new DraggableGroup()
  ..installAll (queryAll ('.some-group-of-draggables-2'));

DropzoneGroup dropZone1 = new DropzoneGroup()
  ..installAll (queryAll ('.some-drop-zone-elements'))
  ..accept.add (draggables1);

DropzoneGroup dropZone2 = new DropzoneGroup()
  ..installAll (queryAll ('.some-drop-zone-elements'))
  ..accept.add (draggables2);
```

There's omitted code for setting up the onDrag, onDrop, etc., but this sets up the premise of the issue.  The DropzoneGroup accepts whichever first DraggableGroup is used, but ignores the second.  Upon trying to use the second, it seems to then cancel the first, with neither DraggableGroup instances accepted.

**Comment by marcojakob** [comment]
If I understand correctly, you are trying to connect two different draggable groups to the _same dropzone elements_. You should create only one dropzone group. Try this:

``` dart
DraggableGroup draggables1 = new DraggableGroup()
..installAll (queryAll ('.some-group-of-draggables-1'));

DraggableGroup draggables2 = new DraggableGroup()
..installAll (queryAll ('.some-group-of-draggables-2'));

DropzoneGroup dropZone1 = new DropzoneGroup()
..installAll (queryAll ('.some-drop-zone-elements'))
..accept.addAll ([draggables1, draggables2]);
```

**Comment by jbaxe2** [comment]
Thanks for the quick response.  I tried to explain the issue as best as I could, sorry if it was confusing.  You are understanding it correctly.  I did what you suggested, and set it up so there's only one shared DropzoneGroup instance.  Getting the same result.

It didn't work at all when I did addAll with the list of both draggables, but works the same as before when I do an add with each draggable individually.

The actions of either draggables1 or draggables2 will be honored for whichever set of elements is dropped first.  Then attempting to drag from the other set of draggables, drops will be ignored.  Switching back to the first draggables set will then be ignored.

I will play around with it some more, I must be doing something wrong, if this should be working.

**Comment by jbaxe2** [comment]
I also mis-typed my original post, the install's should have been installAll with the query of elements.

**Comment by jbaxe2** [comment]
Took a lot of revisions of my code, but got it working.  Closing the issue.

**Comment by marcojakob** [comment]
I've corrected the mis-typing in your question and in my response above.

Does the `html5_dnd` library work correctly? Or did you just find a workaround?

**Comment by jbaxe2** [comment]
The library is working correctly.  My code before was set up to work with HTML5 native drag-n-drop, and the way I had it, didn't play nice with this library.  Took some good finagling, but it works perfectly fine now, including when compiled to JavaScript.

**Comment by marcojakob** [comment]
Great, thank you for the respons. I'm glad to hear that!

2013/9/23 jbaxe2 notifications@github.com
