### ISSUE TITLE
html5_dnd is incompatible with js-interop and the latest SDK

### ISSUE THREAD

**Issue by danschultz** [marcojakob/dart-html5-dnd#13]
The version of html5_dnd on pub forces version `meta: >=0.5.13 <0.5.14`. Even though it's not listed in their pubspec, js-interop needs version 0.7.4 of meta for the `@proxy` metadata tag. So running pub install will error.

What's interesting, is in your pubspec, you allow any version of meta, but when you download the archive from pub, it has the version constrained. Maybe this happens when you run `pub publish` with a version _any_?

Perhaps if you add `meta: '>=0.5.13'` to the pubspec it won't be overwritten by pub publish? This is actually the [convention](http://pub.dartlang.org/doc/dependencies.html#version-constraints) described by pub for library packages.

**Comment by marcojakob** [comment]
I've removed the dependency on meta as it is not really needed. Could you verify that the new version 0.3.4 works for you?
