### ISSUE TITLE
SVG Doesn't Support Draggable

### ISSUE THREAD

**Issue by danschultz** [marcojakob/dart-html5-dnd#7]
Looks like this is a browser limitation. It could be emulated by html5-dnd though.

**Comment by marcojakob** [comment]
Would it be enough if we added a check for `if (_emulateDraggable || element is SvgElement)` when installing a new `element` in [this line](https://github.com/marcojakob/dart-html5-dnd/blob/master/lib/src/dnd/draggable.dart#L154)?

**Comment by danschultz** [comment]
> Would it be enough if we added a check for element is SvgElement when installing a new element in this line?

Indeed, I'll be adding it soon to my fork. You should see a PR in a couple days :)

**Comment by marcojakob** [comment]
Great. Would be perfect if you could add a small svg example in the [test folder](https://github.com/marcojakob/dart-html5-dnd/tree/master/test) to verify that svg is working. (hmm.... github is very slow at the moment)

**Comment by danschultz** [comment]
Doesn't look like this is as easy as I thought. If you're emulating a drag, it also expects dropping to be emulated. However, emulation looks to be a global setting. So calling `DroppableGroup.install()` will never use emulation for SVG elements.

Do you have any suggestions to implement this cleanly?

**Comment by marcojakob** [comment]
You're right, I forgot about this: The `DropzoneGroup` only listens to the emulated events if the browser does not (completely) support HTML5 drag and drop or if touch events are used. As the `DropzoneGroup` can't know if it will ever receive SVG elements, we'd probably need a flag forcing it to always install as emulated dropzone. But we need to be careful here to not make the API more complicated than necessary.

**Comment by danschultz** [comment]
> As the DropzoneGroup can't know if it will ever receive SVG elements, we'd probably need a flag forcing it to always install as emulated dropzone.

`DropzoneGroup` could register the events when a drag is initiated.
